region = "eu-central-1"
profile = "jorge-martins"
bucket_name = "ev-charging-sessions-1050497-lake"
environment = "dev"
glue_database_name = "ev_sessions_bronze"
glue_crawler_name  = "ev-sessions-raw-crawler"
athena_workgroup_name = "ev-sessions-wg"
athena_user_name = "jorge-martins"